### ISSUE TITLE
Newline handling

### ISSUE THREAD

**Issue by Benau** [HOST-Oman/libraqm#106]
Take this follow string as example: U"الصعوبة: مبتدئ\nGame mode: سباق عاديّ"

after raqm_layout with it the 1st glyph is the "\n" in cluster, and the remaining glyphs have no more cluster with newline anymore.

Is it possible for libraqm to split new line itself and it return glyph infos with (visual glyphs of (الصعوبة: مبتدئ)), then a inivisble glyph with \n cluster, and then (visual glyphs of (Game mode: سباق عاديّ))?

Or I have to split it myself? (Because raqm has no intention to support newline in the near future?)

**Comment by khaledhosny** [comment]
You need to split yourself, Raqm expects a single paragraph (since the BiDi algorithm works on one paragraph at a time and our output is a single unbroken line). You should split at any paragraph separator (`\n`, `\r`, `\r\n`, or even the probably unused in the wild U+2029 PARAGRAPH SEPARATOR).

**Comment by Benau** [comment]
thank you
