### ISSUE TITLE
OSError: invalid face handle

### ISSUE THREAD

**Issue by Belval** [HOST-Oman/libraqm#107]
Using `libraqm0` and `libraqm-dev` on Ubuntu 18.04, the library throws a font error.

`OSError: invalid face handle`

I use it through Pillow, it seems to be this string that causes the issue: `بروة`. When I remove the library, the character is printed, but obviously the characters are from left to right instead of right to left.

Is that an issue you encountered before? The font I am using is `NotoSansArabic-Regular.ttf`

EDIT: When I run it a few times, it usually end up working. Any ideas?

**Comment by khaledhosny** [comment]
Please provide steps to reproduce the issue.

**Comment by Belval** [comment]
Right, if I get you a docker container that can reliably reproduce the issue would that work?

**Comment by khaledhosny** [comment]
It wouldn't help immediately since I don't have a working Linux machine right now (only Windows but I'm not looking forward for the adventure of running docker on it).
