### ISSUE TITLE
[Question] Any resources for using libraqm with QPainter?

### ISSUE THREAD

**Issue by hellozee** [HOST-Oman/libraqm#113]
I am trying to have SVG2 text support in Krita. As of now we are using QTextLayout for rendering text. But QTextLayout doesn't offer a lot of features demanded by the SVG2 text specification. Also Qt doesn't allows to explicitly allows accessing harfbuzz/freetype afaik.

For testing out libraqm with QPainter, I put a rough example [here](https://github.com/hellozee/qt-libraqm-test). I followed the QtHarfbuzzExample which I found [here](https://github.com/khaledhosny/QtHarfBuzzExample/blob/master/QtHarfBuzzExample.cc). But as of now it seems the glyph positions returned by harfbuzz and libraqm are different.

Observe the spacing difference on different font sizes with libraqm,

### This one is with 36pt
![](https://i.imgur.com/gtqVQ3u.png)

### This one is with 99pt
![](https://i.imgur.com/3o8RPD0.png)

Would love if anyone could drop a pointer for knowing what I am doing wrong, even better would be if possible can share any examples, :smile:

**Comment by Fahad-Alsaidi** [comment]
I did small test, so I modified your example to use Harfbuzz directly instead of raqm. The result is same. So it is not relate to Raqm or harfbuzz. It is mostly the way you draw the glyphs. Try not use paintEvent and see.

**Comment by hellozee** [comment]
For testing out, I modified the existing code to draw to a QImage and save it first, the results are same. Though the thing which is to be noted here, when I did the harfbuzz example I used a scaling factor while determining the positions as you can see [here](https://github.com/hellozee/qt-harfbuzz-test/blob/master/hbwrapper.cc#L46). Now since the positions returned by libraqm was different I couldn't figure out a proper way to replace the scaling factor, so I just removed it from there. Now in lower sizes it gives some awkward results but in bigger font size it seems to look okay.

**Comment by hellozee** [comment]
Okay, I fixed the issue, by scaling up the font while feeding it into the freetype and scaling it down while calculating the positions, I don't know why I have to do it, probably will try asking this on the freetype mailing list.

**Comment by hellozee** [comment]
The difference can be seen [here](https://github.com/hellozee/qt-libraqm-test/blob/master/layoutengine.cc#L17) and [here](https://github.com/hellozee/qt-libraqm-test/blob/master/layoutengine.cc#L42)

**Comment by khaledhosny** [comment]
With scaling you get subpixel (fractional) positions, which would make a
noticeable difference in smaller sizes because rounding to full pixels
would have a more visible effect.

>

**Comment by hellozee** [comment]
Ahh, correct, I am so dumb, :smile:
