### ISSUE TITLE
missing src/configure?

### ISSUE THREAD

**Issue by enigma9o7** [HOST-Oman/libraqm#116]
I tried to build following the instructions, but there is no ./configure in src directory.

Maybe I don't understand?

**Comment by Fahad-Alsaidi** [comment]
see #61,  #91 & #98

**Comment by enigma9o7** [comment]
Thanks so much.  Seems the solution is to use a release tarball instead of cloning from git.... now gotta find it....

**Comment by enigma9o7** [comment]
I grabbed the latest source tarball, 0.70, and it doesn't include configure either.

**Comment by Fahad-Alsaidi** [comment]
It is there but not it src folder. 
After extract  the release tarball run the terminal inside it.
