### ISSUE TITLE
Installation failed on MacOS Catalina

### ISSUE THREAD

**Issue by SunHaozhe** [HOST-Oman/libraqm#124]
I struggled to install `libraqm` but did not succeed. 

To reproduce:

1. `brew install freetype harfbuzz fribidi gtk-doc`
2. `export XML_CATALOG_FILES="/usr/local/etc/xml/catalog"`
3. `cd /Users/xxx/Desktop/libraqm-master`
4. `./autogen.sh`
5. `./configure`
6. `make`

The first 5 steps were executed without error, when I executed the 6th step `make`. I saw the error:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
  CC       libraqm_la-raqm.lo
raqm.c:1923:24: error: overlapping comparisons always evaluate to true [-Werror,-Wtautological-overlap-compare]
      if (ch != 0x102B || ch != 0x102C || ch != 0x1038 ||
          ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
raqm.c:1926:25: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]
          (ch <= 0x109A && ch >= 0x109C) || ch != 0x1A61 || ch != 0x1A63 ||
           ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
raqm.c:1925:41: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]
          ch != 0x1083 || (ch <= 0x1087 && ch >= 0x108C) || ch != 0x108F ||
                           ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
raqm.c:1924:59: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]
          (ch <= 0x1062 && ch >= 0x1064) || (ch <= 0x1067 && ch >= 0x106D) ||
                                             ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
raqm.c:1924:25: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]
          (ch <= 0x1062 && ch >= 0x1064) || (ch <= 0x1067 && ch >= 0x106D) ||
           ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
5 errors generated.
make[2]: *** [libraqm_la-raqm.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Can you please help me debug this installation issue? Thanks a lot!

Some additional information is shown below:

I am under MacOS Catalina Version `10.15.7`

```
% brew info freetype

freetype: stable 2.10.4 (bottled)
Software library to render fonts
https://www.freetype.org/
/usr/local/Cellar/freetype/2.10.4 (64 files, 2.3MB) *
  Poured from bottle on 2020-11-15 at 11:08:49
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/freetype.rb
License: FTL
==> Dependencies
Required: libpng ✔
==> Analytics
install: 371,836 (30 days), 826,121 (90 days), 2,273,673 (365 days)
install-on-request: 17,144 (30 days), 35,379 (90 days), 86,929 (365 days)
build-error: 0 (30 days)
```

```
% brew info harfbuzz

harfbuzz: stable 2.7.2 (bottled), HEAD
OpenType text shaping engine
https://github.com/harfbuzz/harfbuzz
/usr/local/Cellar/harfbuzz/2.7.2 (68 files, 6.2MB) *
  Poured from bottle on 2020-11-15 at 11:08:54
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/harfbuzz.rb
License: MIT
==> Dependencies
Build: meson ✘, ninja ✘
Required: cairo ✔, freetype ✔, glib ✔, gobject-introspection ✔, graphite2 ✔, icu4c ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 147,902 (30 days), 556,100 (90 days), 1,827,026 (365 days)
install-on-request: 34,139 (30 days), 117,581 (90 days), 215,273 (365 days)
build-error: 0 (30 days)
```

```
% brew info fribidi 

fribidi: stable 1.0.10 (bottled)
Implementation of the Unicode BiDi algorithm
https://github.com/fribidi/fribidi
/usr/local/Cellar/fribidi/1.0.10 (67 files, 609KB) *
  Poured from bottle on 2020-11-15 at 11:08:57
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/fribidi.rb
License: LGPL-2.1
==> Analytics
install: 118,464 (30 days), 386,634 (90 days), 1,493,086 (365 days)
install-on-request: 1,280 (30 days), 4,186 (90 days), 22,247 (365 days)
build-error: 0 (30 days)
```

```
% brew info gtk-doc 

gtk-doc: stable 1.32 (bottled)
GTK+ documentation tool
https://gitlab.gnome.org/GNOME/gtk-doc
/usr/local/Cellar/gtk-doc/1.32_2 (322 files, 6.1MB) *
  Poured from bottle on 2020-11-15 at 11:09:00
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gtk-doc.rb
==> Dependencies
Build: itstool ✘, pkg-config ✔
Required: docbook ✔, docbook-xsl ✔, gettext ✔, libxml2 ✔, python@3.9 ✔, source-highlight ✔
==> Analytics
install: 1,425 (30 days), 2,301 (90 days), 7,226 (365 days)
install-on-request: 871 (30 days), 1,568 (90 days), 3,857 (365 days)
build-error: 0 (30 days)
```

```
% brew info gcc

gcc: stable 10.2.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
/usr/local/Cellar/gcc/9.1.0 (1,461 files, 278.7MB) *
  Built from source on 2019-06-10 at 18:16:40
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gcc.rb
License: GPL-3.0
==> Dependencies
Required: gmp ✔, isl ✔, libmpc ✘, mpfr ✘
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 88,197 (30 days), 276,128 (90 days), 1,227,724 (365 days)
install-on-request: 40,269 (30 days), 124,092 (90 days), 589,033 (365 days)
build-error: 0 (30 days)
```

**Comment by nulano** [comment]
Looks like a #115 duplicate.

**Comment by SunHaozhe** [comment]
@nulano While I am not sure if this is a #115 duplicate, reading it did not help me resolve the problem. It seems to suggest editing the source code.

I followed installation instructions from README but it did not work. Is this project still maintained or is it a problem of my computer?

**Comment by nulano** [comment]
Sorry for the confusion. my comment was aimed at the Raqm developers, not you.
I don't actually work on Raqm, I only have notifications enabled because of its use in Pillow, noticed this looked familiar and left a link to the previous issue.

What I would do in your situation is try to build Raqm without the `-Werror` parameter to change the errors back to a warning.
A quick search suggests that `./configure --disable-Werror` might work: https://github.com/HOST-Oman/libraqm/blob/4ebfcd4121cb1796f7391d34d0a59a579d01505e/m4/ax_compiler_flags.m4#L136-L139
Alternatively, `CFLAGS=-Wno-error make` might also work.

> Is this project still maintained or is it a problem of my computer?

Based on information in #115, it sounds like this is an incompatibility between Raqm and the clang compiler starting with version 10 (default on recent macOS), caused by a bug in Raqm. I am not one of the maintainers, so I don't know if Raqm is still being maintained, but since the [last commit from December 2019](https://github.com/HOST-Oman/libraqm/commits/master) there have only been [6 other issue reports](https://github.com/HOST-Oman/libraqm/issues?q=is%3Aissue+created%3A%3E2019) with #115 the only one not yet resolved, suggesting that it is still being maintained.

**Comment by SunHaozhe** [comment]
@nulano Thanks a lot, this resolved the problem.

To help others who will have the same problem, the installation sequence can be

1. `brew install freetype harfbuzz fribidi gtk-doc`
2. `export XML_CATALOG_FILES="/usr/local/etc/xml/catalog"`
3. `cd /xxx/yyy/zzz/libraqm-master`
4. `./autogen.sh`
5. `./configure --disable-Werror`
6. `make`
7. `make install`
8. `make check`
