### ISSUE TITLE
crash on _raqm_free_text_info

### ISSUE THREAD

**Issue by mrcasty** [HOST-Oman/libraqm#128]
Hi, 

`_raqm_free_text_info` is crashing when I call `_raqm_set_text` with a longer text than then previous one

I seems like `_raqm_set_text` changes text_len:

`  rq->text_len = len;`

before calling `_raqm_free_text_info` which iterates `text_len` elements of `text_info` freeing them.

so if text_len is bigger than the previously initialized array it tries to free garbage.

Or I'm using this in the way I should not...

**Comment by khaledhosny** [comment]
> Or I'm using this in the way I should not...

Each `raqm_t` should be used for one paragraph and be destroyed after that, they were not designed to be resettable.

**Comment by mrcasty** [comment]
Why is _raqm_free_text_info called then ?

**Comment by khaledhosny** [comment]
I’m not sure I get your question. `_raqm_free_text_info()` is an internal function that is called by `raqm_destroy()` to free the allocated memory.

**Comment by mrcasty** [comment]
`_raqm_free_text_info()` it also called in `_raqm_set_text` which makes no much sense if `_raqm_t` is a one use only structure. 

Nevermind, I was just only trying to understand the code.

Thank you

**Comment by khaledhosny** [comment]
I‘m not sure what code you are looking at, but we don’t have a `_raqm_set_text()` function (we have `raqm_set_text()`, though), further more the only place we call `_raqm_free_text_info()` is `raqm_destroy()` which itself is never called internally but should be called by client code after finishing with the `raqm_t`.

**Comment by khaledhosny** [comment]
Oops, I think you are right. Hmm, that does not make sense indeed.

**Comment by niello** [comment]
https://github.com/HOST-Oman/libraqm/pull/147 should fix this. Sorry but I can find how to set a linked issue once I finished creating PR.
