### ISSUE TITLE
[Feature request] There is no per-glyph direction information

### ISSUE THREAD

**Issue by mrcasty** [HOST-Oman/libraqm#129]
hi,

In order to know between which logical characters I should position the cursor when the user clicks on the text, I need to know the direction of every glyph. 

With fribidi only, I used to get the output of `fribidi_get_bidi_types`. But now everything happens inside `raqm_layout` and it does not export the types of the logical character.

I would like raqm glyph list also had a raqm equivalent to `FriBidiCharType`

**Comment by khaledhosny** [comment]
You need the resolved direction, so `fribidi_get_bidi_types()` is not enough. We have that information though, but I’m not sure how to expose it. Unfortunately we prematurely made `raqm_glyph_t` public with no mechanism to extend it with breaking API, so we can’t use it.

**Comment by FlorianDenis** [comment]
Any thoughts on how we could expose it ? I would be interested in getting extracting a few pieces of information as well, specifically: 
- Overall text resolved direction (`rq->resolved_dir`)
- Per glyph direction and script (currently living in `rq->runs`)

Maybe exposing an API to get the runs themselves would be enough, and would not necessitate breaking `raqm_glyph_t`
I'd me willing to write the code if you give directions on the architecture

**Comment by khaledhosny** [comment]
Yes, I think accessor functions would be fine, without having to change `raqm_glyph_t`. I don’t have any strong feeling about the API, so whatever works for you should be fine.
