### ISSUE TITLE
Trying to use libraqm in docker container (Debian)

### ISSUE THREAD

**Issue by vishalchalana** [HOST-Oman/libraqm#130]
I use Pillow on docker container and need raqm for drawing Hindi text. Here's how my dockerfile looks

FROM python:3.9.4-slim
...
RUN apt-get update
RUN apt-get install -y libraqm_dev
...

This works fine but in some instances of my container, I get "Core dumped". Am I not doing something right?

Thanks!

**Comment by nulano** [comment]
This is more likely to be a Pillow issue than a Raqm issue. There were some changes in Pillow 8.2.0 to address issues that could cause a core dump. Could you make sure you are using Pillow 8.2.0? If that doesn't fix the issue, please open an issue on the Pillow issue tracker: https://github.com/python-pillow/Pillow/issues

**Comment by vishalchalana** [comment]
You are absolutely right! I was using an older version of Pillow and upgrading it to 8.2.0 solved the issue. Thanks so much for your help!!
