### ISSUE TITLE
Can't install libraqm following the instructions in README.md

### ISSUE THREAD

**Issue by colibrisson** [HOST-Oman/libraqm#131]
After having successfully installed the dependencies, when I execute the ./configure inside the libraqm directory I get the following error:
`bash: ./configure: No such file or directory`
I tried autoconf but I get the following error:
`configure.ac:7: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:8: error: possibly undefined macro: AM_SILENT_RULES
`

**Comment by khaledhosny** [comment]
You should build from the release tar all not from git checkout.
