### ISSUE TITLE
[Feature Request] Support SheenBidi

### ISSUE THREAD

**Issue by nullgemm** [HOST-Oman/libraqm#138]
Hi, I am developing a simple widget toolkit (working copy [here](https://github.com/nullgemm/razorbeard)) and plan on using libraqm to help with the text rendering, but the FriBiDi dependency worries me a little.

Anything using LGPL code must be released in a way that allows re-linking it with a modified version, and I try my best to write software everyone can use without limitations other than some form of attribution, which is possible under the Apache, MIT and BSD licenses, but not with the GPL or the LGPL.

If my understanding is correct, you guys (or at least @khaledhosny) know about [SheenBiDi](https://github.com/Tehreer/SheenBidi), which is Apache-licensed and could replace FriBiDi. Do you plan on supporting it? If yes, when will that happen? If not, would it be reasonable for me to fork libraqm?

Thank you for your work on this library :)

EDIT:
It looks like I'm not the first one to bring this up: https://github.com/Tehreer/SheenBidi/issues/10

**Comment by khaledhosny** [comment]
I’m open to supporting SheenBiDi as alternative to FriBiDi, but I don't have time to do it myself currently, but I’ll try to review any PRs.

**Comment by nullgemm** [comment]
> Meson support in SheenBidi would be nice of course, and an option to switch between bidi libraries

Ok, thanks! SheenBidi's maintainer already started working on Meson support (https://github.com/Tehreer/SheenBidi/issues/12)

> I don’t get the point about static binaries, as we don’t statically link to any of our dependencies by default

Actually my point was that we currently build `libraqm.so` but not `libraqm.a`. Since we can't always statically link FriBiDi in our apps (because of the LGPL) it kind of made sense to just dynamically link everything so far. If however we make libraqm use SheenBidi then apps can statically link everything and it would be helpful to also generate `libraqm.a`. Am I missing something?

**Comment by khaledhosny** [comment]
That is a standard meson feature, by default it builds only shared libraries, but you can control it with `--default-library` option.

**Comment by nullgemm** [comment]
Oh, right. I guess everything's clear then :)

**Comment by nullgemm** [comment]
It turns out adding utf16 support (needed by ualyze) requires making lots of other changes I am not very comfortable with so this is another dead end for me. I will stop here and clean what I have so far for SheenBidi to open a PR. Just tell me if you prefer `ifdefs` or one extra source file per Bidi library to separate the different versions of the functions affected by this change.
