### ISSUE TITLE
Text rotation broken with freetype 2.11

### ISSUE THREAD

**Issue by remicollet** [HOST-Oman/libraqm#141]
Reported on Fedora 35, using libraqm 0.7.2 and freetype 2.11

When `HAVE_FT_GET_TRANSFORM` is defined, text rotation is broken

Disabling this part solves the issue.

Link (with reproducer)
Initial user report https://github.com/libgd/libgd/issues/790
Fedora issue tracker: https://bugzilla.redhat.com/show_bug.cgi?id=2022957

**Comment by khaledhosny** [comment]
This was introduced to fix #123. May be it needs some tweaks, or may be the glyphs are now doubly transformed (once by Raqm and once elsewhere).

**Comment by khaledhosny** [comment]
https://github.com/libgd/libgd/issues/790#issuecomment-982894815
