### ISSUE TITLE
Letter spacing(Tracking) and word spacing

### ISSUE THREAD

**Issue by therahedwig** [HOST-Oman/libraqm#166]
So, I could technically implement these outside of raqm, but I would like to get them into raqm because they're very common features for text layout (though, admittedly I've seen letter-spacing mostly used by type-setters to counteract terrible kerning).

- Letter spacing is officially applied after bidi, so I guess we can just apply it after shaping.
- It's also a case of 'between this and the next letter.' on both sides of a character.
- Finally, joined scripts/letters should not have this.
- Word spacing is according to the CSS spec only applied to 'Word-separator characters', but not to typographical spaces. This is not the same as unicode class Zs, because this includes em-space (a typographical space), but not stuff like "Phoenician word separator (U+1091F)"... I guess I'll check what the browsers are doing here.

How should we implement this? Because it's one thing to say 'on the left of this character and the right of that character there should be this much space', but I don't know what'll happen after bidi reordering with these values.

Should it perhaps be a function applied *after* layout() is run?

Suggested API (percentage is based on the character the spacing applies to):
- `bool raqm_set_letter_spacing(raqm_t *rq, size_t spacing, bool percentage, size_t start, size_t length)`
-  `bool raqm_set_word_spacing(raqm_t *rq, size_t spacing,  bool percentage, size_t start, size_t length)`

Furthermore, how should it be exposed? Adding it to the advance, or just separate inter-character values?

- [CSS definition](https://www.w3.org/TR/css-text-3/#spacing).

**Comment by khaledhosny** [comment]
It should be done on the glyphs after hb_shape is called.

For letterspacing, you will need a list of scripts where letter spacing makes no sense and do nothing in this case (I don’t know if such list exists and AFAIK browsers don’t currently make such distinction).

For RTL runs, I think the extra space need to be add to both advance width and offset, for LTR it should be added only to advance width.

**Comment by therahedwig** [comment]
> It should be done on the glyphs after hb_shape is called.
> 
> For letterspacing, you will need a list of scripts where letter spacing makes no sense and do nothing in this case (I don’t know if such list exists and AFAIK browsers don’t currently make such distinction).

Hm... Between this and the fact that apparantly indic scripts have a different way of deciding what counts as something that needs letterspacing applied, I guess it might be better to try and avoid being smart. Will mention the joined-scripts limitation in the docs, though.

> 
> For RTL runs, I think the extra space need to be add to both advance width and offset, for LTR it should be added only to advance width.

Well, the glyphs that roll out of harfbuzz don't have negative advance as far as I can tell, they're in 'visual order' instead of 'logical', but I'll try to see what happens if I just go for it.

> Word spacing is according to the CSS spec only applied to 'Word-separator characters', but not to typographical spaces. [...] I guess I'll check what the browsers are doing here.

So, Gecko/Firefox has space, non-breaking-space, tab and also \r and \n (these last three are weird here), while webkit tries to use the list in the css-specs... somewhere I can't actually find where they get assigned as word separators, though I did find it used to have the css word separator list.
