### ISSUE TITLE
Baseline alignment

### ISSUE THREAD

**Issue by therahedwig** [HOST-Oman/libraqm#167]
Again something I could implement separately, but given it affects spacing and is a common feature, it might be best to have inside raqm.

- So, a number of the baselines defined by CSS are directly related to OpenType baselines, that Harfbuzz can retrieve for us. The rest need to be calculated based on the inline-box, and can proly not really be done inside raqm (for my purposes anyway, as SVG text layout has additional rules for creating inline boxes beyond line-breaking ones).
- CSS differentiates between a dominant baseline and an alignment baseline, but the major difference between the two is whether or not they can be inherited, so I think we can simplify these to a single value.
- Finally there's baseline-shift, which can either be a length value, a string like super/sub, and then inline also defines several values that rely on the inline box (and I'll have to handle outside of raqm). Super/sub should use font metrics and otherwise be 1/3rd and 1/5th of the parent font EM. (Maybe I should calculate these outside raqm as well?)
- [Baseline changes affect shaping](https://www.w3.org/TR/css-text-3/#boundary-shaping), so I guess runs need to be split during itemization when the baseline changes?

Suggested api:

- `bool raqm_set_baseline(raqm_t *rq, char* baseline_tag, size_t start, size_t length)`
- `bool raqm_set_baseline_shift(raqm_t *rq, size_t shift, size_t start, size_t length)`
- `bool raqm_set_baseline_shift_super(raqm_t *rq, size_t start, size_t length)` 
- `bool raqm_set_baseline_shift_sub(raqm_t *rq, size_t start, size_t length)`

For implementation, add the relevant values to the textinfo, and then calculate the offset after shaping? Should this baseline offset be added to the `offset`, or should we perhaps create a seperate `cursor-pos` value that's applied to the text-pos before placing the glyph and adding the advance?

Finally, Harfbuzz 4.0 has several useful functions for baselines with fallbacks, should we ifdef this, or just upgrade the dependency?

- [Harfbuzz baseline functions](https://harfbuzz.github.io/harfbuzz-hb-ot-layout.html#hb-ot-layout-get-baseline)
- [Harfbuzz metric functions (super/sub)](https://harfbuzz.github.io/harfbuzz-hb-ot-metrics.html)
- [CSS definition](https://www.w3.org/TR/css-inline-3/#alignment)
- [Horizontal in vertical problem baselines](https://github.com/w3c/csswg-drafts/issues/5424)

**Comment by khaledhosny** [comment]
> For implementation, add the relevant values to the textinfo, and then calculate the offset after shaping? Should this baseline offset be added to the `offset`, or should we perhaps create a seperate `cursor-pos` value that's applied to the text-pos before placing the glyph and adding the advance?

That is a good question, and it shows that we are stretching Raqm way beyond it is original design (a simple library for simple clients that don’t need much formatting). We can’t currently extend `raqm_glyph_info_t` as it would break our ABI, so shifting the offset is probably our best option.

May be it is time to start re-thinking Raqm API for a major version break.



> Finally, Harfbuzz 4.0 has several useful functions for baselines with fallbacks, should we ifdef this, or just upgrade the dependency?

We currently prefer using the minimum dependency version that provide what we need, some clients hate ifdef'd functionality.

**Comment by therahedwig** [comment]
> May be it is time to start re-thinking Raqm API for a major version break.
Yeah, there's a number of other advanced layout features that could use this, like the horizontal-in-vertical, and we, the Krita project, decided that our end-goal would be to let artists layout comic bubbles, and that kinda means Ruby Annotations at some point.

> We currently prefer using the minimum dependency version that provide what we need, some clients hate ifdef'd functionality.
Ok, I'll do that then, I seem to be kind of bad at ifdefing anyway.

**Comment by therahedwig** [comment]
hurm, I've been trying to check how dominant and alignment interact, but the longer I look, the less I understand.

So, from the basics, I get that dominant baseline sets the default for alignment-baseline, so in the end you end up with one value. However, looking through everything, it seems this alignment is done on the span, and not on the characters, so if the second or third character uses a fallback font it would still use the same alignment as the first.

So I'm stuck with the following:

1. I want to do baseline alignment inside raqm because the harfbuzz function uses the script/language, and baseline changes break the runs.
2. However baseline alignment is done by comparing the baselines of two fonts, which raqm may not know about.
3. I could calculate the baseline alignment outside raqm using only fonts and set that with baseline-shift, but then I don't know the script, which I first need to run raqm for so raqm can detect that.

I think my best bet is to calculate the baseline alignment before running the layout, but then set script to 'unknown', and hope for the best. This does mean that the baseline function I made is unnecessary and should be removed...

Of note is that it seems browsers only implement dominant baseline (in svg, not in html/css), but not alignment baseline, which is weird, given the former doesn't actually do anything...

**Comment by therahedwig** [comment]
So, it turns out that CSS baseline alignment only makes sense when it's applied tree-wise, so I can't implement this in Raqm. Once you accept that, it's pretty easy though.
