### ISSUE TITLE
Different font files generate a different result for the same text with raqm_get_glyphs

### ISSUE THREAD

**Issue by jessican1** [HOST-Oman/libraqm#174]
Hello!
I've got a problem where two different font files find a different amount of glyphs in the same string. Shouldn't they find the same amount?

The example I'm running is with this text string in Myanmar: မ္မ မြ

I have modified tests/test-3.test in your test catalog to give me the glyph information for that particular string for the fonts NotoSans-Regular.ttf and NotoSansMyanmar-Regular.ttf.

My problem is that NotoSansRegular returns this:  
Glyph information:
+glyph [0]	x_offset: 0	y_offset: 0	x_advance: 1229	font: Noto Sans
+glyph [0]	x_offset: 0	y_offset: 0	x_advance: 1229	font: Noto Sans
+glyph [0]	x_offset: 0	y_offset: 0	x_advance: 1229	font: Noto Sans
+glyph [2362]	x_offset: 0	y_offset: 0	x_advance: 532	font: Noto Sans
+glyph [0]	x_offset: 0	y_offset: 0	x_advance: 1229	font: Noto Sans
+glyph [0]	x_offset: 0	y_offset: 0	x_advance: 1229	font: Noto Sans

And NotoSansMyanmar returns this:
 Glyph information:
+glyph [29]	x_offset: 0	y_offset: 0	x_advance: 676	font: Noto Sans Myanmar
+glyph [273]	x_offset: -18	y_offset: -24	x_advance: 0	        font: Noto Sans Myanmar
+glyph [3]	x_offset: 0	y_offset: 0	x_advance: 260	font: Noto Sans Myanmar
+glyph [47]	x_offset: 0	y_offset: 0	x_advance: 229	font: Noto Sans Myanmar
+glyph [29]	x_offset: 0	y_offset: 0	x_advance: 676	font: Noto Sans Myanmar

So NotoSansRegular finds 6 glyphs and the space in the string is glyph number 4 (glyph [2362]). But NotoSansMyanmar finds 5 glyphs and the space in the string is glyph number 3 (glyph [3]). 

When looking at the string, the first letter should consist of 2 glyphs, the space is 1 glyph and the final letter is made of 2 glyphs.
Is there a wrong calculation happening for NotoSansRegular since it finds 6 glyphs here?

**Comment by khaledhosny** [comment]
NotoSansRegular doesn't support the Myanmar code points, so it is returning glyph index 0 (AKA `.notdef`) for each if them. If you try to render this, you should get empty squares or something similar.

**Comment by khaledhosny** [comment]
This string contains six code points:
```
Browser 	Codepoint 	Name 	# Fonts 	Script
မ 	U+1019 	MYANMAR LETTER MA 	17 	Myanmar
္ 	U+1039 	MYANMAR SIGN VIRAMA 	17 	Myanmar
မ 	U+1019 	MYANMAR LETTER MA 	17 	Myanmar
	U+0020 	SPACE 	23982 	Common
မ 	U+1019 	MYANMAR LETTER MA 	17 	Myanmar
ြ 	U+103C 	MYANMAR CONSONANT SIGN MEDIAL RA 	15 	Myanmar
```

Noto Sans Myanmar supports them and two of them make a ligature or some other substitution so you get five glyphs, while Not Sans does not support them and simply gives glyph index 0 for each unsupported code point, so you get a number of glyphs matching the number of code points.

**Comment by jessican1** [comment]
Thank you so much for looking into this and for the detailed explanation!
Seems like both fonts are doing their version of what's correct then, so all good!
