### ISSUE TITLE
Installation of raqm and printing of tamil language characters

### ISSUE THREAD

**Issue by HitheshSankararaman** [HOST-Oman/libraqm#177]
Downloaded the zip folder of code and unzipped it.
Gave the command :- **sudo apt-get install libfreetype6-dev libharfbuzz-dev libfribidi-dev meson gtk-doc-tools**
Then gave :- **meson build**
Got the below error

Build started at 2022-09-15T13:08:38.685854
Main binary: /usr/bin/python3
Build Options:
Python system: Linux
The Meson build system
Version: 0.53.2
Source dir: /home/hitheshsankararaman/libraqm-master
Build dir: /home/hitheshsankararaman/libraqm-master/build
Build type: native build

meson.build:1:0: ERROR: Meson version is 0.53.2 but project requires >= 0.56.0

1) Got the above error while building raqm . How to rectify ?

2)  
![c907b492-c814-43e6-8bf4-7657926eff41](https://user-images.githubusercontent.com/67585744/190345557-470690fe-b505-4b71-bc08-ffad9b2c165f.jpg)

**The tamil words in x-axis are not printed correctly.**
Eg:- சொல்லுங்க

Will raqm be able to rectify this error ?

**Comment by HitheshSankararaman** [comment]
> > Downloaded the zip folder of code and unzipped it. Gave the command :- **sudo apt-get install libfreetype6-dev libharfbuzz-dev libfribidi-dev meson gtk-doc-tools** Then gave :- **meson build** Got the below error
> > Build started at 2022-09-15T13:08:38.685854 Main binary: /usr/bin/python3 Build Options: Python system: Linux The Meson build system Version: 0.53.2 Source dir: /home/hitheshsankararaman/libraqm-master Build dir: /home/hitheshsankararaman/libraqm-master/build Build type: native build
> > meson.build:1:0: ERROR: Meson version is 0.53.2 but project requires >= 0.56.0
> > 
> > 1. Got the above error while building raqm . How to rectify ?
> 
> Install meson 0.56.0 or newer. But you probably can `sudo apt-get install libraqm` instead of building it from source.
> 
> > ![c907b492-c814-43e6-8bf4-7657926eff41](https://user-images.githubusercontent.com/67585744/190345557-470690fe-b505-4b71-bc08-ffad9b2c165f.jpg)
> > **The tamil words in x-axis are not printed correctly.** Eg:- சொல்லுங்க
> > Will raqm be able to rectify this error ?
> 
> No idea what application is this, but this is a question best directed to the application developers.

Installed raqm using the command **sudo apt-get install libraqm-dev** . 
Even after installing it shows 'raqm': None . 
**Output of mplcairo.get_versions()**
{'python': '3.9.12 (main, Jun 1 2022, 11:38:51) \n[GCC 7.5.0]', 'mplcairo': '0.5', 'matplotlib': '3.5.3', 'cairo': '1.16.0', 'freetype': '2.11.0', 'pybind11': '2.10.0', 'raqm': None, 'hb': None}

**Comment by khaledhosny** [comment]
That is a question to mplcairo developers, I can’t help you much with that.
