### ISSUE TITLE
Unable to link on MacOS

### ISSUE THREAD

**Issue by timorton-ososim** [HOST-Oman/libraqm#178]
I am unable to link Libraqm in Xcode on MacOS. I have followed the instructions in the ReadMe to build libraqm for MacOS, added the search header path and the search include patch to my project Build Settings, and added libraqm.0.dylib to the Build Phase, Link Library with Binaries.

The build fails with error:
> ld: library not found for -lraqm

<img width="1489" alt="Screenshot 2022-10-10 at 15 23 44" src="https://user-images.githubusercontent.com/46673390/194888570-af787e1e-8b2f-48cd-a57f-9c407cc14884.png">

(Stackoverflow question: https://stackoverflow.com/questions/73960192/how-can-i-link-libraqm-in-xcode-on-macos)

Also: As well as the dynamic library `libraqm.0.dylib` being created, static library `libraqm-test.a` was also created - is this appropriate to use to statically link libraqm in MacOS, or is this for testing purposes only?

**Comment by khaledhosny** [comment]
Sorry, I don’t know anything about XCode to be helpful here. The test static library is for testing and it enables extra logging which you definitely don’t want, but you can instruct meson to build a static library if that it what you want (I believe using `-Ddefault_library=static`).
