### ISSUE TITLE
Build with AppVeyor CI

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/libraqm#19]
To catch MSVC specific errors.

**Comment by khaledhosny** [comment]
See appveyor branch for an almost complete attempt, it builds successfully but fails to find FreeType during link.

**Comment by Fahad-Alsaidi** [comment]
@khaledhosny any update on this?

**Comment by khaledhosny** [comment]
The last build is here:
https://ci.appveyor.com/project/HOSTOman/libraqm/build/1.0.36

There is a weird error with the configure script I can’t reproduce locally, which is blocking further work.
