### ISSUE TITLE
Create a PPA for Raqm

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/libraqm#41]
We need to provide a PPA for Raqm to help with building projects using in on Travis CI.

**Comment by khaledhosny** [comment]
PPA created for some time now: https://launchpad.net/~as-bahanta/+archive/ubuntu/raqm.

**Comment by ChillarAnand** [comment]
apt-get update fails with 
```
E: Failed to fetch http://ppa.launchpad.net/as-bahanta/raqm/ubuntu/dists/zesty/main/binary-amd64/Packages  404  Not Found
```

**Comment by Fahad-Alsaidi** [comment]
@ChillarAnand trusty is only supported right now.

**Comment by ChillarAnand** [comment]
If you tell me what needs to be done, I would be happy to support xenial.
