### ISSUE TITLE
how to install section

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [HOST-Oman/libraqm#44]
libraqm should has a clear instruction how to install it in different OSs and from source code.

**Comment by khaledhosny** [comment]
We use a standard autotools build system, so build instructions should be the standard ones. But I think we need to try building it on Windows and document that as it can be tricky.

**Comment by Fahad-Alsaidi** [comment]
even though it is a standard, we should mention it because nowadays  people use different building system such as cmake.

**Comment by khaledhosny** [comment]
I think this is addressed now.
