### ISSUE TITLE
Add NMake based build system for Windows

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/libraqm#49]
Similar to behdad/harfbuzz#164, so that people can build on Windows with MSVC without needing autotools.

**Comment by ideasman42** [comment]
Maybe better/easier to add CMake support?

**Comment by khaledhosny** [comment]
The idea was to not have to maintain two independent build systems (NMake files would be mainly generated from autotools build). But our build is pretty simple, so if one contributes a CMake build I don’t mind accepting it.

**Comment by Ident** [comment]
CMake makes more sense imo, since this could be configured to work on all platforms without much hassle.

**Comment by Fahad-Alsaidi** [comment]
I think this bug is obsolete since we have cmake build for [libraqm](https://github.com/HOST-Oman/libraqm-cmake)
