### ISSUE TITLE
make check fails with mingw-w64 (x86_64)

### ISSUE THREAD

**Issue by JPeterMugaas** [HOST-Oman/libraqm#60]
I was compiling libragm 1.1 with the mingw-w64 Win64 compiler (included with MSYS2) and I got some test failures.  I including the test.log
[test-suite.log.txt](https://github.com/HOST-Oman/libraqm/files/311437/test-suite.log.txt)

**Comment by khaledhosny** [comment]
The test suits assumes a UTF-8 locale, which does not seem to be the case on Windows and it is causing text encoding issues as you can see from the log that the Arabic text is replaced with question marks. No idea how this should be handled on Windows.

**Comment by JPeterMugaas** [comment]
I think part of this is that the library might need to use the Windows Widechar functions.  Windows NT-systems are based on Unicode which is then translated into something like ASCII or UTF8 as well as other things such as Aribic.  You might try using CP_UTF8 as a codepage parameter.

MultiByteToWideChar - https://msdn.microsoft.com/en-us/library/windows/desktop/dd319072(v=vs.85).aspx

WideCharToMultiByte - https://msdn.microsoft.com/en-us/library/windows/desktop/dd374130(v=vs.85).aspx

There may some other functions involved.  It might not always be a good idea to depend upon what a user sets for there locale sometimes.  Anyway, this is just off the top of my head for what it's worth.

**Comment by khaledhosny** [comment]
The library itself works fine, the problem with the test suit is that we read test input from text files then pass it to the `raqm-test` command line utility on the command line, and this will work only on a UTF-8 locale.

One way to fix this is to modify the `raqm-test` utility to read its arguments from the text file, which should work regardless of the system locale.

I also think there is a way to set the cmd encoding to UTF-8, which might be a simpler work around but I don’t remember how exactly.

**Comment by khaledhosny** [comment]
See http://stackoverflow.com/a/388500

**Comment by Fahad-Alsaidi** [comment]
This bug is fixed by using [libraqm-cmake ](https://github.com/HOST-Oman/libraqm-cmake)
