### ISSUE TITLE
Configuration problems

### ISSUE THREAD

**Issue by Hume2** [HOST-Oman/libraqm#61]
OS: Ubuntu 14.04

I downloaded it. The latest commit from git.
Then I did "autoconf".
```
configure.ac:7: error: possibly undefined macro: AM_INIT_AUTOMAKE
     If this token and others are legitimate, please use m4_pattern_allow.
     See the Autoconf documentation.
configure.ac:8: error: possibly undefined macro: AM_SILENT_RULES
configure.ac:11: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS
configure.ac:35: error: possibly undefined macro: AM_CONDITIONAL
```
Then I did "./configure".
```
./configure: line 1844: syntax error near unexpected token `foreign'
./configure: line 1844: `AM_INIT_AUTOMAKE(foreign color-tests -Wall -Wno-portability)'
```
And that's all. No makefile was generated. Am I first who discovered this bug or I did something wrong?

**Comment by Hume2** [comment]
Sorry for silly bug report. The key was to run autogen.sh before.

**Comment by khaledhosny** [comment]
If you downloaded the release tarball, you shouldn’t run `./autogen.sh` at all, just run `./configure` directly.

**Comment by Hume2** [comment]
Thanks for info.
