### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by illume** [HOST-Oman/libraqm#64]
Hello,

Is there windows support for this library?

I'm from the pygame project.  We're trying to evaluate if we can include it for our release with the next couple of weeks.

best regards,

**Comment by khaledhosny** [comment]
The code builds on Wondows with both GCC and MSVC, if this is the kind of support you are asking about. The build system uses autotools, which works on Windows but not the most user friendly, we have #62 for an alternative CMake build system but it needs someone to finish it.

**Comment by khaledhosny** [comment]
It should follow the standard way of building an autotools package.

**Comment by illume** [comment]
Ok, thanks :)

**Comment by Fahad-Alsaidi** [comment]
@illume if you use msys2, things will be  easier.

**Comment by Fahad-Alsaidi** [comment]
@illume any update from your side about pygame and support RTL languages?

**Comment by Fahad-Alsaidi** [comment]
I think we can close this bug now, since we can build libraqm natively on window by:

1. build raqm-dependencies from this [repository](https://github.com/HOST-Oman/raqm-dependencies).
2. build libraqm itself by using cmake build system from this [repository](https://github.com/HOST-Oman/libraqm-cmake)

**Comment by illume** [comment]
Thanks for the info. I'm sorry I didn't get back to you. We have a preliminary patch, but still need someone to finish the work off of building the dependency and testing it out. Unfortunately we haven't been able to find someone with free time, and have so many other fires to fix in our project.

**Comment by weirman** [comment]
@illume Could you tell me whether pygame supports libraqm. thank you.
