### ISSUE TITLE
Allow setting the text language

### ISSUE THREAD

**Issue by brawer** [HOST-Oman/libraqm#68]
Could Raqm support an API function for setting the text language? Its implementation would simply call `hb_language_from_string()` followed by `hb_buffer_set_language()`. The `lang_bcp47` parameter would be an [IETF BCP47 language code](https://www.w3.org/International/articles/language-tags/).

```c
bool raqm_set_language (raqm_t *rq, const char *lang_bcp47,
                        size_t start, size_t len);
```

The text language can affect OpenType rendering, for example to choose localized letterforms for Simplified versus Traditional Chinese, Bulgarian versus Russian, etc.

I'd love adding a popup menu to [FontView](https://github.com/googlei18n/fontview) that shows the language systems supported by a font. Populating this menu would be no problem, but the current Raqm API doesn't allow me to set the language of the text being rendered.

**Comment by khaledhosny** [comment]
Sure, that was simply overlooked.

**Comment by khaledhosny** [comment]
I opened #69 for this, would be great if you can get it a try before I merge it.

**Comment by brawer** [comment]
Thank you! I’ve added a language popup to FontView in https://github.com/googlei18n/fontview/commit/272775a3d009532964bde81bed4e322b34401519 which calls `raqm_set_language()`, and it works perfect. I was only running into one small issue: in its current form, this Raqm function can’t really be used with UTF-8 text. In my case, the entire buffer is in the same language, so I’m passing 0 for `start` and the buffer size for `len`. Because the function wants the offsets in UTF-32 space, I had to convert the text to UTF-32 outside Raqm. It’s not really a problem, and the documentation also mentions it. But it does limit the usability of the function a bit. Perhaps it might be worth to add a function that returns the length of the text in a raqm_t?

**Comment by khaledhosny** [comment]
In hindsight, I think we should use input string indices so I modified the function and the documentation to this effect. If we are going to support UTF-8 input we better make it as seamless as possible. Adding function that returns the number of characters would be nice nevertheless.
