### ISSUE TITLE
Add API for setting harfbuzz load flags for a hb_font_t

### ISSUE THREAD

**Issue by Ident** [HOST-Oman/libraqm#74]
Currently raqm offers no way of setting the load flags for a loaded harfbuzz/Freetype font. This can be problematic if using non-default flags, such as forced auto hinting ( `FT_LOAD_FORCE_AUTOHINT` ), which is quite commonly used.

Please add an interface to set the flags by calling `hb_ft_font_set_load_flags`

**Comment by khaledhosny** [comment]
Please test and let me know if this does what you want.
