### ISSUE TITLE
33 test failures? this can't be, can it?

### ISSUE THREAD

**Issue by themaddoctor** [HOST-Oman/libraqm#80]
```
FAIL: features-arabic.test
PASS: features-kerning.test
PASS: features-ligature.test
FAIL: scripts-backward.test
FAIL: scripts-backward-ltr.test
FAIL: scripts-backward-rtl.test
FAIL: scripts-forward.test
FAIL: scripts-forward-ltr.test
FAIL: scripts-forward-rtl.test
FAIL: languages-sr.test
FAIL: languages-sr-ru.test
FAIL: multi-fonts.test
FAIL: multi-fonts2.test
FAIL: xyoffset.test
FAIL: test1.test
FAIL: test2.test
FAIL: test3.test
FAIL: test4.test
PASS: test5.test
FAIL: test1_LTR.test
FAIL: test2_LTR.test
FAIL: test3_LTR.test
FAIL: test4_LTR.test
PASS: test5_LTR.test
FAIL: test1_RTL.test
FAIL: test2_RTL.test
FAIL: test3_RTL.test
FAIL: test4_RTL.test
PASS: test5_RTL.test
FAIL: cursor_position1.test
FAIL: cursor_position2.test
FAIL: cursor_position3.test
FAIL: cursor_position4.test
PASS: cursor_position_GB3.test
FAIL: cursor_position_GB4.test
FAIL: cursor_position_GB5.test
FAIL: cursor_position_GB8a.test
FAIL: cursor_position_GB9.test
FAIL: cursor_position_GB9a.test
============================================================================
Testsuite summary for Raqm 0.3.0
============================================================================
# TOTAL: 39
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  33
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to https://github.com/HOST-Oman/libraqm/issues
============================================================================
```

[test-suite.log](https://github.com/HOST-Oman/libraqm/files/1617411/test-suite.log)

**Comment by khaledhosny** [comment]
What platform are you building on and what locale? Looks like you have command line encoding issues.

**Comment by themaddoctor** [comment]
linux, gcc 7.1.0, LANG=en_US.UTF-8

But after compiling, I tried "make check" with LANG=C also. Same errors.

**Comment by khaledhosny** [comment]
You need a UTF-8 locale, but looks like that is already the case so I’m not sure. What is the output of `locale`?

**Comment by themaddoctor** [comment]
LANG=en_US.UTF-8
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=POSIX

**Comment by khaledhosny** [comment]
I think these `POSIX` locale categories are the culprit, they should be set to a UTF-8 locale instead. `LC_ALL=en_US.UTF-8 make check` should do the trick.

 Out of curiosity, what distro has these defaults?

**Comment by themaddoctor** [comment]
It's an LFS. I copied my .bashrc from either the instructions, or from
my old system.

I'll try that now.

**Comment by themaddoctor** [comment]
Yes, all pass.

I admit I was sloppy in setting up my environment, and that I forgot about it.

Thanks for the advice.

**Comment by themaddoctor** [comment]
Thanks again. I knew it had to be something simple. Closing the issue.

**Comment by khaledhosny** [comment]
You are welcomed 🙂
