### ISSUE TITLE
raqm cannot be built (without fiddling with the build scripts) without gtk-doc

### ISSUE THREAD

**Issue by anntzer** [HOST-Oman/libraqm#82]
The readme suggests (perhaps not explicitly...) that building the docs (and therefore gtk-doc) is optional in the build process:
```
To build the documentation you will also need:
* [GTK-Doc][4]

...

To build the documentation, pass `--enable-gtk-doc` to the `configure` script.
```

However, to generate the configure script, one needs to first call ./autogen.sh (a standard step of course, but not documented either, as a side note) and that explicitly checks whether gtkdocize is present.  Even after editing that out, there are further places that always try to build the docs.

**Comment by khaledhosny** [comment]
You need gtk-doc if you are building from git (just as you need autoconf and automake etc.), but building from release tarball does not require any of them. Building from release tarballs is the supported way for building with autotools.

**Comment by anntzer** [comment]
Ah, thanks, I finally understood why so many projects have an autogen.sh/bootstrap even though their README says to use the standard ./configure && make && make install...

Just in case you're interested to add some more projects to the README: https://github.com/anntzer/mplcairo is a rendering backend for Matplotlib (the most commonly used Python plotting library) that can use raqm for text layout.  (Right now none of the backends that ship by default with Matplotlib support complex text layout.)

**Comment by khaledhosny** [comment]
Thanks, added in 7cddb47c6f37bda79b4706853f12c8893eba53ff.
