### ISSUE TITLE
Question: Possible bug?

### ISSUE THREAD

**Issue by molikto** [HOST-Oman/libraqm#83]
Hello!

Thanks for the great library! I learned a lot from this.

As there is no channel for discussion, I want to ask you about a line of code:

```
    hb_buffer_set_flags (run->buffer, HB_BUFFER_FLAG_BOT | HB_BUFFER_FLAG_EOT);
```

Will this cause any problem? It seems from how the flag named, they should only be used for the start/end of paragraph. So if you have a paragraph of text with mixed fonts then only the start segment and the end segment should have flags like this?

**Comment by khaledhosny** [comment]
HarfBuzz is smart enough to apply these flags to the start and end of text, not just the start and end of buffer. Raqm always takes full paragraph (otherwise bidi will be broken) and passes that down to HarfBuzz even when shaping individual runs of text inside the paragraph.
