### ISSUE TITLE
How to safe downgarde from 6 to 5 version 

### ISSUE THREAD

**Issue by semenov-k** [HOST-Oman/libraqm#85]
I build latest libraqm (v6) for using into [Pillow](https://github.com/python-pillow/Pillow), but i get an error:
`OSError: invalid face handle`.
Pillow [recomended](https://github.com/python-pillow/Pillow/blob/master/depends/install_raqm.sh) use libraqm v5 and i have a question, how to downgrade (or just uninstall) current version library?
(Build according to your [instruction](https://github.com/HOST-Oman/libraqm/blob/master/README))
**Plaform: Linux (Debian 9)** #

**Comment by khaledhosny** [comment]
That last Raqm release is 0.5.0, there is no 0.6.0 release if that is what you mean.

**Comment by khaledhosny** [comment]
If you built from git master, just run `make uninstall`, then build 0.5.0 from the latest release tarball.

**Comment by semenov-k** [comment]
Thanks for help.
