### ISSUE TITLE
Uninstallation 

### ISSUE THREAD

**Issue by mostafaasadi** [HOST-Oman/libraqm#86]
Hi
How can I uninstall raqm totally ?
it installed by [pillow installer](https://github.com/python-pillow/pillow-depends)
```
➜  ~ whereis libraqm
libraqm: /usr/lib/libraqm.so /usr/lib/libraqm.a /usr/lib/libraqm.la
```

**Comment by khaledhosny** [comment]
This is an issue with the pillow installer since it uses its own build system.
