### ISSUE TITLE
Clipping when rendering Khmer text using Pillow and libraqm

### ISSUE THREAD

**Issue by bluman88** [HOST-Oman/libraqm#87]
I am using the Python library Pillow (5.3.0) to draw Khmer text onto an image using libraqm (0.5.0) for complex layout support (`layout_engine=ImageFont.LAYOUT_RAQM`).

While the glyph shapes are correct when rendered, some text is shifted right and consequently clipped by the bounding box. Compare the first rendering below (using Pillow) with the second (in MS Word). I have shown the bounding box in red.

![Khmer rendered by Pillow](https://imgur.com/4MrTbo8.png)

![Khmer rendered by MS Word](https://imgur.com/j8JNocE.png)

Code to reproduce clipping effect:

    #!/usr/bin/python3                                                              
    # -*- coding: utf-8 -*-                                                         
    from PIL import Image                                                           
    from PIL import ImageFont                                                       
    from PIL import ImageDraw                                                       
                                                                                    
    img = Image.new("RGB", (512, 512), "white")                                     
    draw = ImageDraw.Draw(img)                                                      
    font = ImageFont.truetype("Battambang-Regular.ttf", 60, layout_engine=ImageFont.LAYOUT_RAQM)                  
    text = "លោកុប្បត្តិ"                                                                 
    draw.text((0, 0), text, (0, 0, 0), font=font)                                   
    img.save('out.png')

I am using the following versions on Ubuntu 18.04:

- Python 3.4.3
- Pillow 5.3.0.dev0 
- libraqm 0.5.0 (from https://github.com/python-pillow/pillow-depends)
- libfreetype6: 2.8.1-2ubuntu2 
- libharfbuzz0b: 1.7.2-1ubuntu1

Any help would be greatly appreciated. I am not sure whether this issue stems from libraqm or one of the other libraries.

**Comment by khaledhosny** [comment]
Raqm does not do the rendering, just the layout. This clipping is likely a Pillow bug and should be reported and fixed there.

**Comment by bluman88** [comment]
Thanks, Khaled. I did wonder whether that might be the case, but I wanted to check whether the offset of the first glyph is given to Pillow by raqm (or FreeType, or something else) as part of the layout.

**Comment by Fahad-Alsaidi** [comment]
There is a [pull request](https://github.com/python-pillow/Pillow/pull/3787) on python-pillow to fix this bug. I think we could now close it.
