### ISSUE TITLE
Remove invisible glyphs

### ISSUE THREAD

**Issue by brawer** [HOST-Oman/libraqm#92]
Could libraqm delete invisible glyphs from the returned glyph array when compiled against a recent HarfBuzz version (which has `hb_buffer_set_invisible_glyph`, introduced in https://github.com/harfbuzz/harfbuzz/commit/e42cd58c997adafca5517faa9aacf651b90520f5 / https://github.com/harfbuzz/harfbuzz/issues/1216)?

In [Unicode’s test suite for rendering engine](https://github.com/unicode-org/text-rendering-tests) I’m using libraqm. Currently, [test case CMAP-1](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#CMAP-1) is failing on the free stack because HarfBuzz inserts an invisible space (by default, HarfBuzz uses `space` as invisible glyph).

I can’t just filter out all spaces in my test harness, because the test suite contains checks that look at the shaping of spaces.

**Comment by khaledhosny** [comment]
`hb_buffer_set_invisible_glyph()` wouldn’t help here since there would still be a glyph even if it is not space glyph (OK, we can use a special glyph id here and filter that, but that is a bit hacky). However, there is `HB_BUFFER_FLAG_REMOVE_DEFAULT_IGNORABLES` which is what you want. We probably need an API that sets this flag, since by default we want to keep them as it allows for simpler output glyph to input text mapping.

**Comment by brawer** [comment]
Indeed, setting `HB_BUFFER_FLAG_REMOVE_DEFAULT_IGNORABLES` would fix my problem. In raqm, what API would you like to see for this? Perhaps the following, which would be similar to raqm’s `raqm_set_freetype_load_flags()` function?

```c
bool
raqm_set_harfbuzz_buffer_flags (raqm_t *rq,
                                int flags);
```

**Comment by khaledhosny** [comment]
I’d rather not expose buffer flags directly, for example we set `HB_BUFFER_FLAG_BOT | HB_BUFFER_FLAG_EOT` unconditionally since we always process full paragraphs. I’d add the following, with negative `gid` meaning drop invisible glyphs:
```C
bool
raqm_set_invisible_glyph (raqm_t *rq,
                          int gid);
```

**Comment by brawer** [comment]
Like this? Maybe a little complex?

For solving my problem in the test suite, it would be sufficient if I could call a libraqm function that makes the invisible glyphs disappear by setting `HB_BUFFER_FLAG_REMOVE_DEFAULT_IGNORABLES`. So I wouldn’t care about specific glyph IDs, but maybe there is a use case?

```c
/**                                                                             
 * raqm_set_invisible_glyph:                                                    
 * @rq: a #raqm_t.                                                              
 * @gid: glyph id to use for invisible glyphs.                                  
 *                                                                              
 * Sets the glyph id to be used for invisible glyhphs.                          
 *                                                                              
 * If @gid is negative, invisible glyphs will be suppressed from the output.    
 * This works on all versions of HarfBuzz.                                      
 *                                                                              
 * If @gid is zero, invisible glyphs will be rendered as space.                 
 * This works on all versions of HarfBuzz.                                      
 *                                                                              
 * If @gid is a positive number, this requires a version of HarfBuzz            
 * that has hb_buffer_set_invisible_glyph(). For older versions, the            
 * return value will be %false and the shaping behavior does not get            
 * changed.                                                                     
 *                                                                              
 * Return value:                                                                
 * %true if no errors happened, %false otherwise.                               
 *                                                                              
 * Since: 0.6                                                                   
 */
bool
hb_buffer_set_invisible_glyph (raqm_t *rq,
                               int gid)
```

**Comment by khaledhosny** [comment]
Sounds good. Yes, the complexity is expected but I think it is OK.
