### ISSUE TITLE
Keep leading digits with Latin text?

### ISSUE THREAD

**Issue by brawer** [HOST-Oman/libraqm#96]
When rendering the string `1BCA` using the [TestMORXEight](https://rawgit.com/unicode-org/text-rendering-tests/master/fonts/TestMORXEight.ttf) font, libraqm splits the string into two runs: one for the digit, another for the letters. In https://github.com/harfbuzz/harfbuzz/issues/1190#issuecomment-429316337, @khaledhosny wrote about this:

> Looks like a bug in Raqm or the script detection algorithm. The digits at the start of the run are assigned Common script instead of Latin and thus ends up in a separate run.

Filing here so it doesn’t get forgotten.

**Comment by khaledhosny** [comment]
Fixed already, see #95.

**Comment by brawer** [comment]
Thank you!
