### ISSUE TITLE
Mention in readme that you need to run autogen.sh

### ISSUE THREAD

**Issue by dwhit** [HOST-Oman/libraqm#98]
Hey I just cloned and tried installing this yesterday and struggled, as I was wondering where the configure script and Makefile were. Eventually I realized I needed to run autogen.sh first. Can you add a line in the readme saying to run it? Thanks!

**Comment by dgboy2000** [comment]
+1 I had the same issue

**Comment by khaledhosny** [comment]
That is a typical autotools setup.
